// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvhtwpigjjpagogvzgpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2aHR3cGlnampwYWdvZ3Z6Z3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjM0MzcsImV4cCI6MjA2MTUzOTQzN30.RkMaUBAddssTK5JSB5o1UMMX8UqiXBaDSAzRF1ChYGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);